name: monthly-webhook-to-feishu

on:
  schedule:
    - cron: '0 2 1 * *'   # 每月1日 02:00 UTC（北京 10:00）
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install deps
        run: |
          pip install -U pandas python-dateutil requests

      - name: Generate monthly summary
        run: |
          python scripts/process_yilian.py || true

      - name: Commit CSV to repo (monthly/YYYY-MM.csv)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          CSV=$(ls -t results/*summary*.csv 2>/dev/null | head -n 1)
          if [ -z "$CSV" ]; then
            echo "No summary CSV found under results/. Abort."
            exit 1
          fi
          MONTH=$(date -u +"%Y-%m")
          mkdir -p monthly
          cp "$CSV" "monthly/${MONTH}.csv"
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add monthly/${MONTH}.csv
          git commit -m "monthly: add ${MONTH}.csv [skip ci]" || echo "No changes to commit"
          git push
          BRANCH=$(git rev-parse --abbrev-ref HEAD)
          echo "CSV_URL=https://raw.githubusercontent.com/${GITHUB_REPOSITORY}/${BRANCH}/monthly/${MONTH}.csv" >> $GITHUB_ENV
          echo "MONTH=${MONTH}" >> $GITHUB_ENV

      - name: Send Feishu Webhook card
        env:
          FEISHU_WEBHOOK_URL:  ${{ secrets.FEISHU_WEBHOOK_URL }}
          FEISHU_WEBHOOK_SECRET: ${{ secrets.FEISHU_WEBHOOK_SECRET }}
          FEISHU_BITABLE_URL: ${{ secrets.FEISHU_BITABLE_URL }}
          CSV_URL: ${{ env.CSV_URL }}
          MONTH:   ${{ env.MONTH }}
        run: |
          python scripts/push_via_webhook.py
