name: Yilian Annual Report

on:
  workflow_dispatch:
    inputs:
      year:
        description: "统计年份（如 2025）。留空或填 ALL 代表全量"
        required: false
        default: "ALL"
  schedule:
    # 每年 1 月 1 日 03:00（UTC）跑上一年年报；如需固定跑“本年”，把脚本参数改为 ALL
    - cron: '0 3 1 1 *'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl

      - name: Run annual aggregation
        env:
          FEISHU_WEBHOOK_URL: ${{ secrets.FEISHU_WEBHOOK_URL }}
          FEISHU_WEBHOOK_SECRET: ${{ secrets.FEISHU_WEBHOOK_SECRET }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python scripts/annual_runner.py --year "${{ github.event.inputs.year || 'ALL' }}"
